[package]
name = "dockerrs"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
bollard = "0.18"
crossterm = { version = "0.28", features = ["event-stream"] }
futures-util = "0.3"
ratatui = "0.29"
tokio = { version = "1", features = ["full"] }
